make_symref: fix set output by abort & non-abort

diff --git a/.github/workflows/make_symref.yml b/.github/workflows/make_symref.yml
--- a/.github/workflows/make_symref.yml
+++ b/.github/workflows/make_symref.yml
@@ -181,7 +181,7 @@ jobs:
           FREETZ_DLTOKEN: ${{ secrets.FREETZ_DLTOKEN }}
         run: |
           make olddefconfig kernel-symref
-          [ -e symref-*.tar.lzma ] || echo "ABORT=true" >> "$GITHUB_OUTPUT"
+          [ -e symref-*.tar.lzma ] && echo "ABORT=false" >> "$GITHUB_OUTPUT" || echo "ABORT=true" >> "$GITHUB_OUTPUT" 
 
       - name: git-diff
         run: |
